[project]
name = "pyobs-task-editor"
version = "0.0.1"
description = "Task editor for pyobs"
authors = [{ name = "Tim-Oliver Husser", email = "thusser@uni-goettingen.de" }]
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "platformdirs>=4.11.0",
    "pyobs>=0.1",
    "pyobs-core>=1.54.4",
    "pyside6>=6.11.1",
    "qt-material>=2.17",
    "qtawesome>=1.4.2",
    "requests>=2.34.2",
]

[project.scripts]
pyobs-task-editor = "pyobs_task_editor.cli:main"

[dependency-groups]
dev = [
    "mypy>=1.15.0,<2",
    "black>=25.1.0,<26",
    "pre-commit>=4.6.1,<5",
    "flake8>=7.3.0",
    "pyside6-stubs>=6.7.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 120
target-version = ['py311']
